# -*- coding: utf-8 -*-
"""panoptic_segmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ooXaxQQ6tRxOUyhhhFF6xVBjh_fABpb6

# File used for panoptic segmentation training and evaluation
## Author: Ankur Chrungoo
"""

from google.colab import drive

drive.mount('/content/drive/', force_remount=True)

# To unzip prepared dataset, uncomment this code (and use when appropriate directory is selected as the current directory)
#!unzip datasets.zip

import os

# Git related code (not always used)
#!git clone https://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@github.com/cankur007/dissertation.git

os.chdir('/content/drive/MyDrive/dissertation/dissertation')

# git repo related code (not to be used always)
#!git push
#!git pull

# Use only for syncing to google drive
#drive.flush_and_unmount()

# Change directory to panoptic-deeplab repo
os.chdir('/content/drive/MyDrive/dissertation/dissertation/src/pdl/panoptic-deeplab')

# Install requirements/dependencies
!pip install -r requirements.txt

# Use for training the panoptic-deeplab model ( baseline)
#!python tools/train_net.py --cfg configs/Base-Panoptic-DeepLab.yaml
!python tools/train_net.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml

# Use only for syncing to google drive
#drive.flush_and_unmount()

# Not needed
#!git config --global user.email ankur.chrungoo@gmail.com

#!git commit -m "updated"

# Install scripts for cityscapes data preparation, evaluation, etc.
!pip install git+https://github.com/mcordts/cityscapesScripts.git

# IMPORTANT! 
# Before training, the data preparation scripts need to be run for cityscapes, as per https://github.com/bowenc0221/panoptic-deeplab/blob/master/datasets/README.md

# use for testing the panoptic-deeplab model
#!python tools/test.py --cfg configs/Base-Panoptic-DeepLab.yaml
!python tools/test.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml

"""**DEMO - Evaluation**"""

# Use for qualitative evaluation purposes
#!python tools/demo.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml \
#    --input-files demo_input \
#    --output-dir output/panoptic_deeplab_R50_bs_1_90K_lr_00005/demo_output \
#    --merge-image \
#    TEST.MODEL_FILE output/panoptic_deeplab_R50_bs_1_90K_lr_00005/final_state.pth

# Use for qualitative evaluation for the converted (dark/night/poor light) data.
!python tools/demo.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml \
    --input-files demo_input_converted \
    --output-dir output/test_converted_val_set_with_original_model/demo_output_converted \
    --merge-image \
    TEST.MODEL_FILE output/test_converted_val_set_with_original_model/final_state.pth

# Use for qualitative evaluation for the converted (dark/night/poor light) data - WITHOUT MERGE
!python tools/demo.py --cfg configs/panoptic_deeplab_R50_os32_cityscapes.yaml \
    --input-files demo_input_converted \
    --output-dir output/test_converted_val_set_with_original_model/demo_output_converted_no_merge \
    TEST.MODEL_FILE output/test_converted_val_set_with_original_model/final_state.pth